version: 2.1

composer_install: &composer_install
  name: Composer install
  command: ./composer.phar install -n

composer_save_cache: &composer_save_cache
  key: composer-cache-{{ checksum "composer.lock" }}
  paths:
    - vendor

composer_restore_cache: &composer_restore_cache
  keys:
    - composer-cache-{{ checksum "composer.lock" }}

jobs:
  build:
    docker:
      - image: ${ACR_HOSTNAME_PD}/alpine-php82-build:latest
        auth:
          username: ${ACR_LOGIN_PD}
          password: ${ACR_PASSWORD_PD}
    resource_class: small
    working_directory: /var/www/html
    steps:
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Set git safe directory
          command: git config --global --add safe.directory /var/www/html
      - checkout
      - restore_cache:
          <<: *composer_restore_cache
      - run:
          <<: *composer_install
      - save_cache:
          <<: *composer_save_cache
      - persist_to_workspace:
          root: /var/www/html
          paths:
            - .

  static:
    docker:
      - image: ${ACR_HOSTNAME_PD}/alpine-php82-build:latest
        auth:
          username: ${ACR_LOGIN_PD}
          password: ${ACR_PASSWORD_PD}
    working_directory: /var/www/html
    resource_class: small
    steps:
      - attach_workspace:
          at: /var/www/html
      - run:
          name: PHPStan
          command: |
            mkdir -p results/PHPStan
            php -d memory_limit=4G vendor/bin/phpstan --error-format=junit > results/PHPStan/result.xml; php -d memory_limit=4G vendor/bin/phpstan
      - run:
          name: PHPCS
          command: |
            mkdir -p results/PHPCS
            vendor/bin/phpcs src
      - store_test_results:
          path: results
      - store_artifacts:
          path: results

  phpunit:
    docker:
      - image: ${ACR_HOSTNAME_PD}/alpine-php82-build:latest
        auth:
          username: ${ACR_LOGIN_PD}
          password: ${ACR_PASSWORD_PD}
    resource_class: small
    working_directory: /var/www/html
    steps:
      - attach_workspace:
          at: /var/www/html
      - run:
          name: PHPUnit
          command: |
            mkdir -p results/PHPUnit
            vendor/bin/phpunit --log-junit results/PHPUnit/phpunit.xml
      - store_test_results:
          path: results
      - store_artifacts:
          path: results

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - ACR_CREDENTIALS
      - phpunit:
          context:
            - ACR_CREDENTIALS
          requires:
            - build
      - static:
          context:
            - ACR_CREDENTIALS
          requires:
            - build
